services:
  # 1. BASE DE DATOS (Con volumen nombrado para persistencia)
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # <- PUNTO 2 DE LA RÚBRICA: Named volume
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. BACKEND DE VENTAS (Ruta corregida para el Pipeline)
  backend-ventas:
    build: ./back-Ventas_SpringBoot/Springboot-API-REST #ruta corregida 
    image: tech_ventas:1.0
    ports:
      - "8080:8080"
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    depends_on:
      mysql:
        condition: service_healthy

  # 3. BACKEND DE DESPACHO (Ruta corregida para el Pipeline)
  backend-despacho:
    build: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO # <- Alineado con el archivo .yml
    image: tech_despacho:1.0
    ports:
      - "8081:8081"
    environment:
      DB_ENDPOINT: ${DB_ENDPOINT}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    depends_on:
      mysql:
        condition: service_healthy

  # 4. FRONTEND (Ruta corregida para el Pipeline)
  frontend:
    build: ./front_despacho # <- Alineado con el archivo .yml
    image: frontend:1.0
    ports:
      - "3000:80"
    depends_on:
      - backend-ventas
      - backend-despacho

# DECLARACIÓN DEL VOLUMEN NOMBRADO
volumes:
  mysql_data: