# Despliegue Backend Ventas
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ventas
spec:
  replicas: 2 # Puedes poner 1 si quieres ahorrar recursos
  selector:
    matchLabels:
      app: backend-ventas
  template:
    metadata:
      labels:
        app: backend-ventas
    spec:
      containers:
        - name: backend-ventas
          image: 123456789012.dkr.ecr.us-east-1.amazonaws.com/innovatech-chile-backend-ventas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_ENDPOINT
              value: "${DB_ENDPOINT}" 
            - name: DB_PORT
              value: "${DB_PORT}"
            - name: DB_NAME
              value: "${MYSQL_DATABASE}"
            - name: DB_USERNAME
              value: "${DB_USERNAME}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_HOST
              value: "${DB_HOST}"
---
# Servicio Backend Ventas (Interno)
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas
spec:
  selector:
    app: backend-ventas
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP