name: Despliegue en AWS con EKS (Innovatech Chile)

on:
  push:
    branches:
      - "develop"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CLUSTER_NAME: innovatech-chile-cluster

    steps:
      - name: Checkout (git clone...)
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Loguear con ECR (elastic container registry)
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Rescatar el AWS Account ID
        run: |
          echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Definir las URL de los ECR
        run: |
          echo "VENTAS_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-chile-backend-ventas" >> $GITHUB_ENV
          echo "DESPACHOS_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-chile-backend-despachos" >> $GITHUB_ENV
          echo "FRONTEND_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-frontend" >> $GITHUB_ENV
          echo "MYSQL_ECR=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/innovatech-chile-mysql" >> $GITHUB_ENV
      
      - name: Build MySQL personalizado
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $MYSQL_ECR:${GITHUB_SHA} \
            ./db \
            --load

      - name: Push MySQL personalizado
        run: |
          docker push $MYSQL_ECR:${GITHUB_SHA}

      - name: Build backend ventas
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $VENTAS_ECR:${GITHUB_SHA} \
            ./back-Ventas_SpringBoot/Springboot-API-REST \
            --load

      - name: Push backend ventas
        run: |
          docker push $VENTAS_ECR:${GITHUB_SHA}

      - name: Build backend despachos
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $DESPACHOS_ECR:${GITHUB_SHA} \
            ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO \
            --load

      - name: Push backend despachos
        run: |
          docker push $DESPACHOS_ECR:${GITHUB_SHA}

      - name: Build frontend
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t $FRONTEND_ECR:${GITHUB_SHA} \
            ./front_despacho \
            --load

      - name: Push frontend
        run: |
          docker push $FRONTEND_ECR:${GITHUB_SHA}
      
      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4

      - name: Configurar EKS a través de GitHub Actions
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $CLUSTER_NAME
            
      - name: Aplicar los manifiestos de kubernetes
        run: |
          kubectl apply -f infra/k8s/
          
      - name: Actualizar imagen de MySQL
        run: |
          kubectl set image deployment/mysql \
            mysql=$MYSQL_ECR:${GITHUB_SHA}

      - name: Actualizar imagen del Backend Despacho
        run: |
          kubectl set image deployment/backend-despacho \
            backend-despacho=$DESPACHOS_ECR:${GITHUB_SHA}

      - name: Actualizar imagen del Backend Ventas
        run: |
          kubectl set image deployment/backend-ventas \
            backend-ventas=$VENTAS_ECR:${GITHUB_SHA}

      - name: Actualizar imagen del Frontend
        run: |
          kubectl set image deployment/frontend \
            frontend=$FRONTEND_ECR:${GITHUB_SHA}
      
      - name: Esperar despliegue de MySQL
        run: |
          kubectl rollout status deployment/mysql

      - name: Esperar despliegue de despacho
        run: |
          kubectl rollout status deployment/backend-despacho
          
      - name: Esperar despliegue de ventas
        run: |
          kubectl rollout status deployment/backend-ventas

      - name: Esperar despliegue del frontend
        run: |
          kubectl rollout status deployment/frontend